name: Deploy to server
on:
  push:
      branches:
        - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copying new files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "/src,/package.json,/tsconfig.json"
          target: ${{ secrets.TARGET_FOLDER }}
          strip_components: 2
      - name: Reloading app
        uses: fifsky/ssh-action@master
        with:
          command: cd ${{ secrets.TARGET_FOLDER }} && npm install && npm run build && pm2 restart blog-api
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          args: "-tt"