name: Deploy to server
on:
  push:
      branches:
        - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - name: copying new files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "build,package.json"
          target: ${{ secrets.TARGET_FOLDER }}
      - name: Reloading app
        uses: fifsky/ssh-action@master
        with:
          command: cd ${{ secrets.TARGET_FOLDER }} && npm install && pm2 restart blog-api
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          args: "-tt"